# encoding: utf-8
require './pieces/piece.rb'
require './pieces/slidingpiece.rb'
require './pieces/steppingpiece.rb'
require './pieces/rook.rb'
require './pieces/queen.rb'
require './pieces/king.rb'
require './pieces/knight.rb'
require './pieces/bishop.rb'
require './pieces/pawn.rb'